export type SentenceChallenge = {
  id: string;
  english: string;
  correct: string[];
  meaning: string;
  type: string;
};

export const SENTENCE_CHALLENGES: SentenceChallenge[] = [
  // A1 Basics (1-20)
  { id: 's-1', english: "I am Jon.", correct: ["Ni", "Jon", "naiz"], meaning: "Subject + Complement + Verb", type: "A1 Basics" },
  { id: 's-2', english: "You are a student.", correct: ["Zu", "ikaslea", "zara"], meaning: "Subject + Noun + Verb", type: "A1 Basics" },
  { id: 's-3', english: "The house is big.", correct: ["Etxea", "handia", "da"], meaning: "Subject + Adjective + Verb", type: "A1 Basics" },
  { id: 's-4', english: "We are friends.", correct: ["Gu", "lagunak", "gara"], meaning: "Plural Subject + Plural Noun + Verb", type: "A1 Basics" },
  { id: 's-5', english: "I am in the house.", correct: ["Ni", "etxean", "naiz"], meaning: "Subject + Inessive + Verb", type: "A1 Location" },
  { id: 's-6', english: "The book is on the table.", correct: ["Liburua", "mahaian", "dago"], meaning: "Subject + Locative + Verb (State)", type: "A1 Location" },
  { id: 's-7', english: "I have a book.", correct: ["Nik", "liburu", "bat", "dut"], meaning: "Ergative + Object + Bat + Aux", type: "A1 Transitive" },
  { id: 's-8', english: "I drink water.", correct: ["Nik", "ura", "edaten", "dut"], meaning: "Ergative + Object + Main Verb + Aux", type: "A1 Daily" },
  { id: 's-9', english: "I am not a doctor.", correct: ["Ni", "ez", "naiz", "medikua"], meaning: "Negation + Aux + Complement", type: "A1 Negation" },
  { id: 's-10', english: "I always study.", correct: ["Nik", "beti", "ikasten", "dut"], meaning: "Ergative + Adverb + Verb + Aux", type: "A2 Time" },
  { id: 's-11', english: "The cat eats an apple.", correct: ["Katuak", "sagar", "bat", "jaten", "du"], meaning: "Ergative + Object + Verb + Aux", type: "A1 Daily" },
  { id: 's-12', english: "My father is at work.", correct: ["Nire", "aita", "lanean", "dago"], meaning: "Genitive + Subject + Locative + Verb", type: "A1 Family" },
  { id: 's-13', english: "I like the mountains.", correct: ["Mendiak", "maite", "ditut"], meaning: "Object (Plural) + Love + Aux", type: "A1 Nature" },
  { id: 's-14', english: "He goes to the town.", correct: ["Hura", "herrira", "doa"], meaning: "Subject + Allative + Verb", type: "A1 Motion" },
  { id: 's-15', english: "We have two cars.", correct: ["Guk", "bi", "auto", "ditugu"], meaning: "Ergative + Number + Noun + Aux", type: "A1 Assets" },
  { id: 's-16', english: "The woman is beautiful.", correct: ["Emakumea", "ederra", "da"], meaning: "Subject + Adjective + Verb", type: "A1 Description" },
  { id: 's-17', english: "I see the city.", correct: ["Nik", "hiria", "ikusten", "dut"], meaning: "Ergative + Object + Verb + Aux", type: "A1 Senses" },
  { id: 's-18', english: "The child plays in the street.", correct: ["Haurra", "kalean", "jolasten", "da"], meaning: "Subject + Locative + Verb", type: "A1 Daily" },
  { id: 's-19', english: "They are from San Sebastian.", correct: ["Haiek", "Donostiakoak", "dira"], meaning: "Subject + Local Genitive + Verb", type: "A1 Origins" },
  { id: 's-20', english: "I want to buy bread.", correct: ["Nik", "ogia", "erosi", "nahi", "dut"], meaning: "Ergative + Object + Verb + Want + Aux", type: "A1 Shopping" },

  // A1-A2 Extended (21-100)
  { id: 's-21', english: "Where is the shop?", correct: ["Non", "dago", "denda?"], meaning: "Interrogative + Verb + Subject", type: "A1 Questions" },
  { id: 's-22', english: "The shop is closed.", correct: ["Denda", "itxita", "dago"], meaning: "Subject + Participle + Verb", type: "A1 State" },
  { id: 's-23', english: "I go to the shop.", correct: ["Ni", "dendara", "noa"], meaning: "Subject + Allative + Verb", type: "A1 Motion" },
  { id: 's-24', english: "The shops are new.", correct: ["Dendak", "berriak", "dira"], meaning: "Plural Subject + Plural Adj + Verb", type: "A1 Plurals" },
  { id: 's-25', english: "The dog is small.", correct: ["Txakurrak", "txikia", "da"], meaning: "Subject + Adjective + Verb", type: "A1 Description" },
  { id: 's-26', english: "The dogs are hungry.", correct: ["Txakurrak", "gose", "dira"], meaning: "Plural Subject + Condition + Verb", type: "A1 Condition" },
  { id: 's-27', english: "I have a green car.", correct: ["Nik", "auto", "berde", "bat", "dut"], meaning: "Ergative + Noun + Adj + Bat + Aux", type: "A1 Description" },
  { id: 's-28', english: "We live in Bilbao.", correct: ["Gu", "Bilbon", "bizi", "gara"], meaning: "Subject + Locative + Live + Aux", type: "A1 Life" },
  { id: 's-29', english: "It is cold today.", correct: ["Gaur", "hotz", "egiten", "du"], meaning: "Adverb + Cold + Do + Aux", type: "A1 Weather" },
  { id: 's-30', english: "I am happy.", correct: ["Pozik", "naiz"], meaning: "Adverb + Verb", type: "A1 Emotion" },
  { id: 's-31', english: "Who are you?", correct: ["Nor", "zara", "zu?"], meaning: "Who + Verb + You", type: "A1 Questions" },
  { id: 's-32', english: "What is this?", correct: ["Zer", "da", "hau?"], meaning: "What + Verb + This", type: "A1 Questions" },
  { id: 's-33', english: "The water is cold.", correct: ["Ura", "hotza", "dago"], meaning: "Subject + Adj + Verb", type: "A1 Description" },
  { id: 's-34', english: "I eat bread and cheese.", correct: ["Nik", "ogia", "eta", "gazta", "jaten", "ditut"], meaning: "Ergative + Obj1 + and + Obj2 + Verb + Aux", type: "A1 Food" },
  { id: 's-35', english: "My house is your house.", correct: ["Nire", "etxea", "zure", "etxea", "da"], meaning: "Possessive + Subj + Possessive + Comp + Verb", type: "A1 Basics" },
  { id: 's-36', english: "He works in a factory.", correct: ["Hura", "fabrika", "batean", "bizi", "da"], meaning: "Subject + Noun + Indef.Loc + Live + Aux", type: "A1 Work" },
  { id: 's-37', english: "The bird flies high.", correct: ["Hegaztiak", "goi", "egiten", "du", "hegan"], meaning: "Subject + High + Do + Aux + Flight", type: "A1 Nature" },
  { id: 's-38', english: "I am reading a book.", correct: ["Ni", "liburu", "bat", "irakurtzen", "ari", "naiz"], meaning: "Subject + Noun + Bat + Read + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-39', english: "They are dancing.", correct: ["Haiek", "dantzan", "ari", "dira"], meaning: "Subject + Dance.Loc + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-40', english: "Can you help me?", correct: ["Lagun", "diezaidakezu?"], meaning: "Help + Aux.Potential", type: "A2 Potential" },
  { id: 's-41', english: "I like to listen to music.", correct: ["Musika", "entzutea", "atsegin", "dut"], meaning: "Music + Listening + Please + Aux", type: "A2 Preferences" },
  { id: 's-42', english: "The tree is green.", correct: ["Zuhaitza", "berdea", "da"], meaning: "Subject + Adj + Verb", type: "A1 Nature" },
  { id: 's-43', english: "I have many books.", correct: ["Nik", "liburu", "asko", "ditut"], meaning: "Ergative + Noun + Many + Aux", type: "A1 Assets" },
  { id: 's-44', english: "Do you have time?", correct: ["Denborarik", "baduzu?"], meaning: "Time.Partitive + Yes-have-you?", type: "A2 Questions" },
  { id: 's-45', english: "I don't have money.", correct: ["Ez", "dut", "dirurik"], meaning: "Neg + Aux + Money.Partitive", type: "A1 Negation" },
  { id: 's-46', english: "Come here!", correct: ["Etorri", "hona!"], meaning: "Come + Here", type: "A1 Commands" },
  { id: 's-47', english: "Wait a moment.", correct: ["Itxaron", "une", "bat."], meaning: "Wait + Moment + Bat", type: "A1 Commands" },
  { id: 's-48', english: "I am tired.", correct: ["Nekatuta", "nago"], meaning: "Tired + Verb", type: "A1 State" },
  { id: 's-49', english: "The sun is hot.", correct: ["Eguzkia", "bero", "dago"], meaning: "Subject + Adj + Verb", type: "A1 Nature" },
  { id: 's-50', english: "Good morning.", correct: ["Egun", "on."], meaning: "Day + Good", type: "A1 Greetings" },
  { id: 's-51', english: "Good night.", correct: ["Gabon."], meaning: "Night-good", type: "A1 Greetings" },
  { id: 's-52', english: "See you later.", correct: ["Gero", "arte."], meaning: "Later + Until", type: "A1 Greetings" },
  { id: 's-53', english: "Thank you very much.", correct: ["Eskerrik", "asko."], meaning: "Thanks.Partitive + Much", type: "A1 Basics" },
  { id: 's-54', english: "You are welcome.", correct: ["Ez", "horregatik."], meaning: "Not + for that", type: "A1 Basics" },
  { id: 's-55', english: "I am sorry.", correct: ["Sentitzen", "dut."], meaning: "Feeling + Aux", type: "A1 Basics" },
  { id: 's-56', english: "How are you?", correct: ["Nola", "zaude?"], meaning: "How + Verb", type: "A1 Questions" },
  { id: 's-57', english: "I am fine.", correct: ["Ondo", "nago."], meaning: "Well + Verb", type: "A1 State" },
  { id: 's-58', english: "The city is noisy.", correct: ["Hiria", "zalapartatsua", "da"], meaning: "Subject + Adj + Verb", type: "A2 Description" },
  { id: 's-59', english: "The mountains are high.", correct: ["Mendiak", "altuak", "dira"], meaning: "Plural Subject + Plural Adj + Verb", type: "A1 Nature" },
  { id: 's-60', english: "I brought an apple.", correct: ["Nik", "sagar", "bat", "ekarri", "dut"], meaning: "Ergative + Obj + Bat + Brought + Aux", type: "A1 Past" },
  { id: 's-61', english: "We ate fish.", correct: ["Guk", "arraina", "jan", "dugu"], meaning: "Ergative + Obj + Eat + Aux", type: "A1 Food" },
  { id: 's-62', english: "She bought a dress.", correct: ["Hark", "soineko", "bat", "erosi", "du"], meaning: "Ergative + Obj + Buy + Aux", type: "A1 Shopping" },
  { id: 's-63', english: "They saw a film.", correct: ["Haiek", "pelikula", "bat", "ikusi", "dute"], meaning: "Ergative + Obj + See + Aux", type: "A1 Entertainment" },
  { id: 's-64', english: "I will go tomorrow.", correct: ["Bihar", "joango", "naiz"], meaning: "Tomorrow + Go.Future + Aux", type: "A2 Future" },
  { id: 's-65', english: "He will come later.", correct: ["Gero", "etorriko", "da"], meaning: "Later + Come.Future + Aux", type: "A2 Future" },
  { id: 's-66', english: "We will play football.", correct: ["Guk", "futbolean", "jolastuko", "dugu"], meaning: "Ergative + Football.Loc + Play.Future + Aux", type: "A2 Future" },
  { id: 's-67', english: "The cat is sleeping.", correct: ["Katua", "lo", "egiten", "ari", "da"], meaning: "Subject + Sleep + Do + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-68', english: "I am learning Basque.", correct: ["Ni", "euskara", "ikasten", "ari", "naiz"], meaning: "Subject + Obj + Learning + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-69', english: "She is working.", correct: ["Hura", "lanean", "ari", "da"], meaning: "Subject + Work.Loc + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-70', english: "The car is blue.", correct: ["Autoa", "urdina", "da"], meaning: "Subject + Adj + Verb", type: "A1 Description" },
  { id: 's-71', english: "The flower is red.", correct: ["Lorea", "gorria", "da"], meaning: "Subject + Adj + Verb", type: "A1 Nature" },
  { id: 's-72', english: "I like apples.", correct: ["Sagarrak", "gustatzen", "zaizkit"], meaning: "Apples.Plural + Pleasing + Verb.to.me", type: "A2 Preferences" },
  { id: 's-73', english: "Do you like coffee?", correct: ["Kafea", "gustatzen", "zaizu?"], meaning: "Coffee + Pleasing + Verb.to.you", type: "A2 Preferences" },
  { id: 's-74', english: "The children are playing.", correct: ["Haurrak", "jolasten", "ari", "dira"], meaning: "Plural Subject + Playing + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-75', english: "I live in a small town.", correct: ["Herri", "txiki", "batean", "bizi", "naiz"], meaning: "Town + Small + Bat.Loc + Live + Aux", type: "A1 Life" },
  { id: 's-76', english: "The sky is gray.", correct: ["Zerua", "grisa", "dago"], meaning: "Subject + Adj + Verb", type: "A1 Nature" },
  { id: 's-77', english: "It is raining.", correct: ["Euria", "ari", "du"], meaning: "Rain + Progressive + Aux", type: "A2 Weather" },
  { id: 's-78', english: "I need help.", correct: ["Laguntza", "behar", "dut"], meaning: "Help + Need + Aux", type: "A1 Basics" },
  { id: 's-79', english: "He wants water.", correct: ["Hark", "ura", "nahi", "du"], meaning: "Ergative + Obj + Want + Aux", type: "A1 Basics" },
  { id: 's-80', english: "We love our family.", correct: ["Guk", "gure", "familia", "maite", "dugu"], meaning: "Ergative + Possessive + Obj + Love + Aux", type: "A1 Family" },
  { id: 's-81', english: "The boy is reading.", correct: ["Mutila", "irakurtzen", "ari", "da"], meaning: "Subject + Reading + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-82', english: "The girl is singing.", correct: ["Neska", "kantatzen", "ari", "da"], meaning: "Subject + Singing + Progressive + Aux", type: "A2 Progressive" },
  { id: 's-83', english: "I have a big dog.", correct: ["Nik", "txakur", "handi", "bat", "dut"], meaning: "Ergative + Noun + Adj + Bat + Aux", type: "A1 Description" },
  { id: 's-84', english: "The table is made of wood.", correct: ["Mahaia", "egurrezkoa", "da"], meaning: "Subject + Wood.Instrumental.Gen + Verb", type: "A2 Description" },
  { id: 's-85', english: "I am from Spain.", correct: ["Espainiakoa", "naiz"], meaning: "Spain.Gen + Verb", type: "A1 Origins" },
  { id: 's-86', english: "Where are you from?", correct: ["Nongoa", "zara?"], meaning: "Where.Gen + Verb", type: "A1 Origins" },
  { id: 's-87', english: "My name is Mikel.", correct: ["Nire", "izena", "Mikel", "da"], meaning: "Possessive + Subj + Name + Verb", type: "A1 Basics" },
  { id: 's-88', english: "I am 20 years old.", correct: ["Hogei", "urte", "ditut"], meaning: "Twenty + Years + Have.Aux", type: "A1 Age" },
  { id: 's-89', english: "The sea is calm.", correct: ["Itsasoa", "lasai", "dago"], meaning: "Subject + Adj + Verb", type: "A1 Nature" },
  { id: 's-90', english: "I like to swim.", correct: ["Igerian", "egitea", "atsegin", "dut"], meaning: "Swimming.Loc + Doing + Please + Aux", type: "A2 Preferences" },
  { id: 's-91', english: "The moon is bright.", correct: ["Ilargia", "distiratsua", "dago"], meaning: "Subject + Adj + Verb", type: "A1 Nature" },
  { id: 's-92', english: "I see stars.", correct: ["Izarrak", "ikusten", "ditut"], meaning: "Plural Obj + See + Aux", type: "A1 Nature" },
  { id: 's-93', english: "The forest is dark.", correct: ["Basoa", "iluna", "da"], meaning: "Subject + Adj + Verb", type: "A1 Nature" },
  { id: 's-94', english: "I am walking.", correct: ["Oinez", "nabil"], meaning: "Foot.Instrumental + Verb.Walking", type: "A2 Motion" },
  { id: 's-95', english: "The bird is singing.", correct: ["Hegaztia", "kantatzen", "ari", "da"], meaning: "Subject + Singing + Progressive + Aux", type: "A2 Nature" },
  { id: 's-96', english: "I have a phone.", correct: ["Nik", "telefonoa", "dut"], meaning: "Ergative + Obj + Aux", type: "A1 Assets" },
  { id: 's-97', english: "The pencil is on the book.", correct: ["Arkatza", "liburuaren", "gainean", "dago"], meaning: "Subject + Book.Gen + Above + Verb", type: "A2 Location" },
  { id: 's-98', english: "I want to sleep.", correct: ["Lo", "egin", "nahi", "dut"], meaning: "Sleep + Do + Want + Aux", type: "A1 Basics" },
  { id: 's-99', english: "The street is long.", correct: ["Kalea", "luzea", "da"], meaning: "Subject + Adj + Verb", type: "A1 Description" },
  { id: 's-100', english: "I brought the apple for the friend.", correct: ["Lagunarentzat", "sagarra", "ekarri", "dut"], meaning: "Friend.the.for + Apple.the + Brought + Aux", type: "A2 Complex" }
];
